language: python
matrix:
  include:
    - os: linux
      # We need an older version of python in order to have compatibility with
      # older versions of libc
      dist: xenial
      python: 3.6
    - os: osx
      language: generic

env:
  jobs:
    - PATH=/tmp/bin/:$PATH

script:
  # In Mac OS python and pip binaries are v2, so we create symlinks
  - mkdir /tmp/bin && ln -s $(which python3) /tmp/bin/python && ln -s $(which pip3) /tmp/bin/pip
  - pip install --upgrade pip setuptools==44.0.0
  - make ci-info
  - make bootstrap-dev-plugins
  - make test
  - make bundle
  - make ci-test-bundle

deploy:
  # Create github release and push binary to github
  - provider: script
    script: make ci-push-bundle
    skip_cleanup: true
    on:
      tags: true